config/routes.rb
Rails.application.routes.draw do
  resources :configuracions

  resources :clients

  resources :payments



  resources :furnitures

  get 'angular/show'
  root 'sales#index'

  resources :sales do
    collection do
      get 'clientsSearch'
      get 'furnitureSearch'
      get 'add_item'
      get 'getFurnitureSale'
      get 'setClient'
      get 'selecDeadlines'
      get 'getDeadlines'
    end
  end


end

app/models/configuracion.rb
class Configuracion < ActiveRecord::Base
    belongs_to :sale
end

app/controllers/configuracions_controller.rb
class ConfiguracionsController < ApplicationController
  before_action :set_configuracion, only: [:show, :edit, :update, :destroy]

  # GET /configuracions
  # GET /configuracions.json
  def index
    @configuracions = Configuracion.all
  end

  # GET /configuracions/1
  # GET /configuracions/1.json
  def show
  end

  # GET /configuracions/new
  def new
    @configuracion = Configuracion.new
  end

  # GET /configuracions/1/edit
  def edit
  end

  # POST /configuracions
  # POST /configuracions.json
  def create
    @configuracion = Configuracion.new(configuracion_params)

    respond_to do |format|
      if @configuracion.save
        format.html { redirect_to @configuracion, notice: 'Configuracion was successfully created.' }
        format.json { render :show, status: :created, location: @configuracion }
      else
        format.html { render :new }
        format.json { render json: @configuracion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configuracions/1
  # PATCH/PUT /configuracions/1.json
  def update
    respond_to do |format|
      if @configuracion.update(configuracion_params)
        format.html { redirect_to @configuracion, notice: 'Configuracion was successfully updated.' }
        format.json { render :show, status: :ok, location: @configuracion }
      else
        format.html { render :edit }
        format.json { render json: @configuracion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configuracions/1
  # DELETE /configuracions/1.json
  def destroy
    @configuracion.destroy
    respond_to do |format|
      format.html { redirect_to configuracions_url, notice: 'Configuracion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuracion
      @configuracion = Configuracion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def configuracion_params
      params.require(:configuracion).permit(:financing_rate, :deadline, :hitch)
    end
end

app/views/configuracions/_form.html.erb
<%= form_for(@configuracion) do |f| %>
  <% if @configuracion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@configuracion.errors.count, "error") %> prohibited this configuracion from being saved:</h2>

      <ul>
      <% @configuracion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :financing_rate %><br>
    <%= f.text_field :financing_rate %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_field :deadline %>
  </div>
  <div class="field">
    <%= f.label :hitch %><br>
    <%= f.text_field :hitch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configuracions/edit.html.erb
<h1>Editing configuracion</h1>

<%= render 'form' %>

<%= link_to 'Show', @configuracion %> |
<%= link_to 'Back', configuracions_path %>

app/views/configuracions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 right-align add-cart">
      <a class="waves-effect waves-light btn" href="/configuracions/new">Nueva configuracion</a>
    </div>
  </div>
    <h1>Configuracio</h1>
    <table>
      <thead>
        <tr>
          <th>Tasa de financiamiento rate</th>
          <th>Fecha tope</th>
          <th>Enganche</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @configuracions.each do |configuracion| %>
          <tr>
            <td><%= configuracion.financing_rate %></td>
            <td><%= configuracion.deadline %></td>
            <td><%= configuracion.hitch %></td>
            <td><%= link_to 'Show', configuracion %></td>
            <td><%= link_to 'Edit', edit_configuracion_path(configuracion) %></td>
            <td><%= link_to 'Destroy', configuracion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<br>

app/views/configuracions/new.html.erb
<div class="container">
    <h1>Nueva configuracion</h1>
    <%= render 'form' %>
    <%= link_to 'Back', configuracions_path %>
</div>

app/views/configuracions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Financing rate:</strong>
  <%= @configuracion.financing_rate %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @configuracion.deadline %>
</p>

<p>
  <strong>Hitch:</strong>
  <%= @configuracion.hitch %>
</p>

<%= link_to 'Edit', edit_configuracion_path(@configuracion) %> |
<%= link_to 'Back', configuracions_path %>