config/routes.rb
Rails.application.routes.draw do
  resources :configuracions

  resources :clients

  resources :payments



  resources :furnitures

  get 'angular/show'
  root 'sales#index'

  resources :sales do
    collection do
      get 'clientsSearch'
      get 'furnitureSearch'
      get 'add_item'
      get 'getFurnitureSale'
      get 'setClient'
      get 'selecDeadlines'
      get 'getDeadlines'
    end
  end


end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_one :configuracion, dependent: :destroy
  has_one :client, dependent: :destroy
  has_many :lineFurnitures, dependent: :destroy
  has_many :furnitures, :through => :lineFurnitures
  accepts_nested_attributes_for :configuracion, :allow_destroy => true
  accepts_nested_attributes_for :lineFurnitures, :allow_destroy => true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  #before_action :set_sale, only: [:show, :edit, :update, :destroy]

  def clientsSearch
    @clubs = Client.where("(name||rfc) LIKE :q", :q => "%#{params[:name]}%") 
    render json: @clubs
  end
  
  def furnitureSearch
    @furnitures = Furniture.where("(name||description) LIKE :q", :q => "%#{params[:queri]}%") 
    render json: @furnitures
  end

  def add_item
    set_sale = Sale.find(params[:saleid])
    configuracion =set_sale.configuracion
    @furniture = Furniture.find(params[:id])
    item = @furniture
    existing_line__furniture = LineFurniture.where("furniture_id = ? AND sale_id = ?", item.id, set_sale.id).first 
    if  existing_line__furniture.blank?
      line_new = LineFurniture.new(:furniture_id=> item.id, :sale_id => set_sale.id, :quantity => 1)
      line_new.price = line_new.furniture.price * (1 + (configuracion.financing_rate * configuracion.deadline) /100)
      line_new.save
      update_line_furniture_totals(line_new)
      update_sale(line_new)
      render json: line_new
    else
      existing_line__furniture.quantity += 1
      existing_line__furniture.save
      update_line_furniture_totals(existing_line__furniture)
      update_sale(existing_line__furniture)
      render json: existing_line__furniture
    end
  end

  def update_sale(lineFurniture)
    set_sale = Sale.find(lineFurniture.sale_id)
    configuracion =set_sale.configuracion
    hitch = configuracion.hitch
    set_sale.encganche = (hitch / 100.to_f) * lineFurniture.total_price
    set_sale.bonificacion = set_sale.encganche * ((configuracion.financing_rate * configuracion.deadline ) /100)
    set_sale.toal=lineFurniture.total_price - set_sale.encganche - set_sale.bonificacion
    set_sale.save
  end


  def update_line_furniture_totals(line_item)
    line_item.total_price = line_item.price * line_item.quantity
    line_item.save
  end

  def getFurnitureSale
     sale = set_sale
     saleOb ={
       sale: sale,
       lineFurnitures: sale.lineFurnitures,
       furnitures: sale.furnitures
     }  
     render json:  saleOb
  end

  def setClient 
    set_sale
    client = Client.find(params[:clientId])
    set_sale.client = client
    set_sale.save
    render json:  set_sale.client
  end

  def getDeadlines
    months = [3,6,9,12]
    result = []
    set_sale
    configuracion = set_sale.configuracion
    counted = set_sale.toal.to_f / (1 + (configuracion.financing_rate * configuracion.deadline) /100) 
    months.each do |p|
      term = counted.to_f * (1 + (configuracion.financing_rate * p) / 100)
      payment = term / p.to_f
      spare = set_sale.toal.to_f - term
      result.push({numero:p, total:term, pago:payment, ahorra:spare })
    end
    render json: result
  end

  def selecDeadlines
    set_sale = Sale.find(params[:id])
    deadlinesId = params[:deadlinesId]
    set_sale.term = deadlinesId
    set_sale.status= true
    set_sale.save
    render json:  set_sale
  end


  
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.where( :status => true)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.create
    @sale.configuracion = Configuracion.last
    @sale.save
    redirect_to :controller => 'sales', :action => 'edit', :id => @sale.id
  end



  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    if @sale.present?
      @sale.status= false
    end
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:payment_id, :toal, :encganche, :bonificacion, :status)
    end
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_id %><br>
    <%= f.number_field :payment_id %>
  </div>
  <div class="field">
    <%= f.label :toal %><br>
    <%= f.number_field :toal %>
  </div>
  <div class="field">
    <%= f.label :encganche %><br>
    <%= f.number_field :encganche %>
  </div>
  <div class="field">
    <%= f.label :bonificacion %><br>
    <%= f.number_field :bonificacion %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<script> 


</script> 
<div class="container" data-ng-controller="NotesCtrl">
<div class="row">
	<div class="col l12">
		<div class="card">
			<div class="card-content">
				<div class="row">
					<div class="col l12 center-align titulo-venta">Registro de venta</div>
					<div class="col l12 right-align folio-venta">Folio: <%= @sale.id %> </div>
					<div class="col l12">
						<div class="col l8">
							<div class="input-field col s12">
								<angucomplete id="ex1"
													placeholder="Clientes"
													pause="100"
													selectedobject="selected.client"
													url="/sales/clientsSearch?name="
													searchfields="name"
													titlefield="name"
													minlength="3"
													inputclass="form-control form-control-small"/>

							</div>
						</div>
						<div class="col l4 folio" ng-if="selected.client">
							RFC de cliente: {{selected.client.originalObject.rfc}}
						</div>
						<div class="col l8">
							<div class="input-field col s12">
								<angucomplete id="productoIput"
															placeholder="Productos"
															pause="100"
															selectedobject="selected.furnishing"
															url="/sales/furnitureSearch?queri="
															searchfields="name"
															titlefield="name"
															minlength="3"
															inputclass="form-control form-control-small"/>
															</div>
						</div>
						<div class="col l4 add-cart">
							<a class="waves-effect waves-light btn" 
								 ng-class="selected.furnishing ? '' : 'disabled'"
								 ng-click="addfurnishing(selected.furnishing)">
								<i class="material-icons left">shopping_cart</i>
							</a>
						</div>
					</div>
					<div class="tabla col l12">
						<table>
							<thead>
								<tr>
									<th>Descrion  Aticulo</th>
									<th>Modelo</th>
									<th>Cantidad</th>
									<th>Precio</th>
									<th>Importe</th>
								</tr>
							</thead>
							<tbody>
								<tr ng-repeat="x in listado.lineFurnitures">
									<td>{{x.furniture_id.description}}</td>
									<td>{{x.furniture_id.description}}</td>
									<td>{{x.quantity}}</td>
									<td>{{x.price}}</td>
									<td>{{x.total_price}}</td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="col l12 pagos">
						<div class="col s4 offset-s8 pago-content right-align">
							<div class="col l12"> 
								<div class="col l6 pago-tile">Enganche:</div>
								<div class="col l6">${{listado.sale.encganche}}</div>
							</div>
							<div class="col l12 pago-content"> 
								<div class="col l6 pago-tile">Bonificacion:</div>
								<div class="col l6">${{listado.sale.bonificacion}}</div>
							</div>
							<div class="col l12 pago-content"> 
								<div class="col l6 pago-tile">Total:</div>
								<div class="col l6">${{listado.sale.toal}}</div>
							</div>
						</div>
					</div>
		
					<div class="plazos col l12" ng-if="fertilizer.assets">
						<table class="striped">
							<thead>
								<tr>
									<th colspan="5" class="center-align abnos-table">Abonos Mensuales</th>
								</tr>
							</thead>
			
							<tbody>
								<tr ng-repeat="deadlines in fertilizer.deadlines">
									<td>{{deadlines.numero}} abonos de </td>
									<td>{{deadlines.pago | currency}}</td>
									<td>Total a pagar de {{deadlines.total | currency}}</td>
									<td>se ahorra ${{deadlines.ahorra | currency}}</td>
									<td> <input name="deadline" type="radio" id="{{deadlines.numero}}"  ng-model="confirmed" ng-checked="selecDeadlines(deadlines)" /></td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="col s6 offset-s6 pago-content right-align">
						<div class="col l6 ">
							<a class="waves-effect waves-light btn"  href="/sales">
							Cancelar
							</a>
						</div >
						<div class="col l6">
							<a class="waves-effect waves-light btn " ng-click="saleNex()" ng-if="!fertilizer.assets">Siguiente</a>
							<a class="waves-effect waves-light btn " ng-click="saveNex()" ng-if="fertilizer.assets">Guardar</a>
						</div >
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/sales/index.html.erb
<div class="container" data-ng-controller="NotesCtrl">
  
  <div class="row">
    <div class="col s12 right-align menu-top"> 
      <a href="/sales/new" class="waves-effect waves-light btn">
        <i class="material-icons left">note_add</i>
        Nueva venta
      </a>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content">
          <table class="striped">
            <thead>
              <tr>
                <th>Folio</th>
                <th>Clave cliente</th>
                <th>Nombre</th>
                <th>Total</th>
                <th>Status</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @sales.each do |sale| %>
                <tr class="table-lik" onclick="document.location = 'sales/<%= sale.id %>';">
                  <td><%= sale.id %></td>
                  <td><%= sale.client.id%></td>
                  <td><%= sale.client.name %></td>
                  <td><%= sale.toal %></td>
                  <td><%= sale.status %></td>
                  <td><%= link_to 'Eliminar', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="container" data-ng-controller="NotesCtrl">
	<div class="row">
		<div class="col l12">
			<div class="card">
				<div class="card-content">
					<div class="row">
						<div class="col l12 center-align">Reguistro de venta</div>
						<div class="col l12 right-align">Folio </div>
						<div class="col l12">
							<div class="col l8">
								<div class="input-field col s12">
									<angucomplete id="ex1"
														placeholder="Clientes"
														pause="100"
														selectedobject="selected.client"
														url="/sales/clientsSearch?name="
														searchfields="name"
														titlefield="name"
														minlength="3"
														inputclass="form-control form-control-small"/>

								</div>
							</div>
							<div class="col l4" ng-if="selected.client">
						    RFC de cliente: {{selected.client.originalObject.rfc}}
							</div>
							<div class="col l8">
								<div class="input-field col s12">
									<angucomplete id="productoIput"
																placeholder="Productos"
																pause="100"
																selectedobject="selected.furnishing"
																url="/sales/furnitureSearch?queri="
																searchfields="name"
																titlefield="name"
																minlength="3"
																inputclass="form-control form-control-small"/>
																</div>
							</div>
							<div class="col l4">
								<a class="waves-effect waves-light btn" 
									 ng-class="selected.furnishing ? '' : 'disabled'"
									 ng-click="addfurnishing(selected.furnishing)">
									<i class="material-icons left">shopping_cart</i>
								</a>
						  </div>
						</div>
						<div class="tabla col l12">
						{{listado}}
							<table>
								<thead>
									<tr>
											<th>Descrion  Aticulo</th>
											<th>Modelo</th>
											<th>Cantidad</th>
											<th>Precio</th>
											<th>Importe</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Pollo</td>
										<td>Eclair</td>
										<td>$0.87</td>
										<td>$0.87</td>
										<td>$0.87</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col l12 pagos">
							<div class="col s4 offset-s8 pago-content right-align">
								<div class="col l12"> 
									<div class="col l6 pago-tile">Enganche:</div>
									<div class="col l6">1300</div>
								</div>
								<div class="col l12 pago-content"> 
									<div class="col l6 pago-tile">Enganche:</div>
									<div class="col l6">1300</div>
								</div>
								<div class="col l12 pago-content"> 
									<div class="col l6 pago-tile">Enganche:</div>
									<div class="col l6">1300</div>
								</div>
							</div>
						</div>


						<div class="plazos col l12">
							<table class="striped">
								<thead>
									<tr>
									  <th colspan="4" class="center-align abnos-table">Abonos Mensuales</th>
									</tr>
								</thead>
				
								<tbody>
									<tr>
										<td>3 abonos de </td>
										<td>$400</td>
										<td>Total a pagar de 300</td>
										<td>se aorra $400</td>
									</tr>
								</tbody>
							</table>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment:</strong>
  <%= @sale.payment_id %>
</p>

<p>
  <strong>Toal:</strong>
  <%= @sale.toal %>
</p>

<p>
  <strong>Encganche:</strong>
  <%= @sale.encganche %>
</p>

<p>
  <strong>Bonificacion:</strong>
  <%= @sale.bonificacion %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sale.status %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>