config/routes.rb
Rails.application.routes.draw do
  resources :configuracions

  resources :clients

  resources :payments



  resources :furnitures

  get 'angular/show'
  root 'sales#index'

  resources :sales do
    collection do
      get 'clientsSearch'
      get 'furnitureSearch'
      get 'add_item'
      get 'getFurnitureSale'
      get 'setClient'
      get 'selecDeadlines'
      get 'getDeadlines'
    end
  end


end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
    has_many   :lineFurniture
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: [:show, :edit, :update, :destroy]

  # GET /furnitures
  # GET /furnitures.json
  def index
    @furnitures = Furniture.all
  end

  # GET /furnitures/1
  # GET /furnitures/1.json
  def show
  end

  # GET /furnitures/new
  def new
    @furniture = Furniture.new
  end

  # GET /furnitures/1/edit
  def edit
  end

  # POST /furnitures
  # POST /furnitures.json
  def create
    @furniture = Furniture.new(furniture_params)

    respond_to do |format|
      if @furniture.save
        format.html { redirect_to @furniture, notice: 'Furniture was successfully created.' }
        format.json { render :show, status: :created, location: @furniture }
      else
        format.html { render :new }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /furnitures/1
  # PATCH/PUT /furnitures/1.json
  def update
    respond_to do |format|
      if @furniture.update(furniture_params)
        format.html { redirect_to @furniture, notice: 'Furniture was successfully updated.' }
        format.json { render :show, status: :ok, location: @furniture }
      else
        format.html { render :edit }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1
  # DELETE /furnitures/1.json
  def destroy
    @furniture.destroy
    respond_to do |format|
      format.html { redirect_to furnitures_url, notice: 'Furniture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture
      @furniture = Furniture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def furniture_params
      params.require(:furniture).permit(:barcode, :name, :description, :price, :cost_price, :status)
    end
end

app/views/furnitures/_form.html.erb
<div class="row">
  <div class="col l12">
    <div class="card">
      <div class="card-content">
        <%= form_for(@furniture) do |f| %>
          <% if @furniture.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>
      
              <ul>
              <% @furniture.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :modelo %><br>
            <%= f.text_field :barcode %>
          </div>
          <div class="field">
            <%= f.label :nombre %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :descripción %><br>
            <%= f.text_area :description %>
          </div>
          <div class="field">
            <%= f.label :precio %><br>
            <%= f.text_field :price %>
          </div>
          <div class="field">
            <%= f.label :precio_de_coste %><br>
            <%= f.text_field :cost_price %>
          </div>
          <div class="card-action right-align">
            <a class="waves-effect waves-light btn" href="/furnitures">
              <i class="material-icons left">reply</i>
              Regresar
            </a>
            <%= f.submit 'Guardar', :class => 'waves-effect waves-light btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m4 l2"><p>Editar articulo</p></div>
    </div>
    <%= render 'form' %>
</div>

app/views/furnitures/index.html.erb
<div class="container" data-ng-controller="NotesCtrl">
  <div class="right-align">
    <a class="waves-effect waves-light btn" href="/furnitures/new"><i class="material-icons left">save</i>Nuevo articulo</a>
  </div>
  <div class="row">
    <div class="col l12">
      <div class="card">
        <div class="card-content">
        <span class="card-title">Artículos registrados</span>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Price</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
              <% @furnitures.each do |furniture| %>
                <tr>
                  <td><%= furniture.name %></td>
                  <td><%= furniture.description %></td>
                  <td><%= furniture.price %></td>
                  <td>
                    <a class='dropdown-button btn' href='#' data-activates='dropdown1'>actions</a>
                      <!-- Dropdown Structure -->
                      <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="furnitures/<%= furniture.id%>"><i class="material-icons">visibility</i>Ver</a></li>
                        <li><a href="furnitures/<%= furniture.id%>/edit"><i class="material-icons">create</i>Editar</a></li>
                        <li><%= link_to 'Eliminar', furniture, method: :delete, data: { confirm: '¿Estás seguro?' } %></li>
                      </ul>

                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/new.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m4 l2"><p>Nuevo articulo</p></div>
    </div>
    <%= render 'form' %>
</div>

app/views/furnitures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barcode:</strong>
  <%= @furniture.barcode %>
</p>

<p>
  <strong>Name:</strong>
  <%= @furniture.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @furniture.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @furniture.price %>
</p>

<p>
  <strong>Cost price:</strong>
  <%= @furniture.cost_price %>
</p>


<%= link_to 'Edit', edit_furniture_path(@furniture) %> |
<%= link_to 'Back', furnitures_path %>